# Generated by Django 2.2.10 on 2021-01-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=60)),
                ('emailId', models.EmailField(max_length=254, unique=True)),
                ('contactNumber', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
