# Generated by Django 2.2.10 on 2021-01-20 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostContent',
            fields=[
                ('postid', models.AutoField(primary_key=True, serialize=False)),
                ('Useremail', models.EmailField(max_length=254)),
                ('content', models.TextField(max_length=1000)),
                ('dateofpost', models.DateTimeField(auto_now_add=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserRegister')),
            ],
        ),
    ]
