# Generated by Django 2.2.10 on 2021-01-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_postcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcontent',
            name='nameOfUser',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
