# Generated by Django 2.2.10 on 2021-01-22 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_postcontent_nameofuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commentid', models.AutoField(primary_key=True, serialize=False)),
                ('commentContent', models.TextField(max_length=1000)),
                ('comment', models.TextField(max_length=1000)),
                ('dateofcomment', models.DateTimeField(auto_now_add=True)),
                ('postid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PostContent')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserRegister')),
            ],
        ),
    ]
