# Generated by Django 2.2.10 on 2021-01-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_userlikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlikes',
            name='userid',
            field=models.IntegerField(default=True),
        ),
    ]
